// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCtyrxz4iczsqNgB44fVT6nm85eqDZuRis',
    appId: '1:612686770899:android:50b9876c82f66c81825a26',
    messagingSenderId: '612686770899',
    projectId: 'gym-track-63fba',
    storageBucket: 'gym-track-63fba.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDy-I3mRhzH-zpI28FlEF9mX-k0vvo5qpo',
    appId: '1:612686770899:ios:1562264cfcfd3a13825a26',
    messagingSenderId: '612686770899',
    projectId: 'gym-track-63fba',
    storageBucket: 'gym-track-63fba.firebasestorage.app',
    iosClientId: '612686770899-0spob3todt2kj75egpqg8f7jehaqkirb.apps.googleusercontent.com',
    iosBundleId: 'com.example.gymTrack',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDZ_KlKZ4TZDvZGNw7dSWbzSK2cadLqF9E',
    appId: '1:612686770899:web:809453c240c353c9825a26',
    messagingSenderId: '612686770899',
    projectId: 'gym-track-63fba',
    authDomain: 'gym-track-63fba.firebaseapp.com',
    storageBucket: 'gym-track-63fba.firebasestorage.app',
    measurementId: 'G-K0E2MLD16R',
  );

}